In [1]:
import pandas as pd  
import numpy as np

In [2]:
# Read the three files into python as dataframes

# Show the DataFrame's shape

In [3]:
file1 = pd.read_csv('file1.csv')
file1.head()

Customer          ST GENDER             Education Customer Lifetime Value  \
0  RB50392  Washington    NaN                Master                     NaN   
1  QZ44356     Arizona      F              Bachelor              697953.59%   
2  AI49188      Nevada      F              Bachelor             1288743.17%   
3  WW63253  California      M              Bachelor              764586.18%   
4  GA49547  Washington      M  High School or Below              536307.65%   

    Income  Monthly Premium Auto Number of Open Complaints     Policy Type  \
0      0.0                1000.0                    1/0/00   Personal Auto   
1      0.0                  94.0                    1/0/00   Personal Auto   
2  48767.0                 108.0                    1/0/00   Personal Auto   
3      0.0                 106.0                    1/0/00  Corporate Auto   
4  36357.0                  68.0                    1/0/00   Personal Auto   

   Vehicle Class  Total Claim Amount  
0  Four-Door Car            2.704934  
1  Four-Door Car         1131.464935  
2   Two-Door Car          566.472247  
3            SUV          529.881344  
4  Four-Door Car           17.269323

In [4]:
file1.shape

(4008, 11)

In [5]:
file2 = pd.read_csv('file2.csv')
file2.head()

Customer          ST GENDER Education Customer Lifetime Value  Income  \
0  GS98873     Arizona      F  Bachelor              323912.47%   16061   
1  CW49887  California      F    Master              462680.11%   79487   
2  MY31220  California      F   College              899704.02%   54230   
3  UH35128      Oregon      F   College             2580706.30%   71210   
4  WH52799     Arizona      F   College              380812.21%   94903   

   Monthly Premium Auto Number of Open Complaints  Total Claim Amount  \
0                    88                    1/0/00               633.6   
1                   114                    1/0/00               547.2   
2                   112                    1/0/00               537.6   
3                   214                    1/1/00              1027.2   
4                    94                    1/0/00               451.2   

      Policy Type  Vehicle Class  
0   Personal Auto  Four-Door Car  
1    Special Auto            SUV  
2   Personal Auto   Two-Door Car  
3   Personal Auto     Luxury Car  
4  Corporate Auto   Two-Door Car

In [6]:
file2.shape

(996, 11)

In [7]:
file3 = pd.read_csv('file3.csv')
file3.head()

Customer       State  Customer Lifetime Value             Education Gender  \
0  SA25987  Washington              3479.137523  High School or Below      M   
1  TB86706     Arizona              2502.637401                Master      M   
2  ZL73902      Nevada              3265.156348              Bachelor      F   
3  KX23516  California              4455.843406  High School or Below      F   
4  FN77294  California              7704.958480  High School or Below      M   

   Income  Monthly Premium Auto  Number of Open Complaints    Policy Type  \
0       0                   104                          0  Personal Auto   
1       0                    66                          0  Personal Auto   
2   25820                    82                          0  Personal Auto   
3       0                   121                          0  Personal Auto   
4   30366                   101                          2  Personal Auto   

   Total Claim Amount  Vehicle Class  
0          499.200000   Two-Door Car  
1            3.468912   Two-Door Car  
2          393.600000  Four-Door Car  
3          699.615192            SUV  
4          484.800000            SUV

In [8]:
file3.shape

(7070, 11)

In [9]:
# Standardize header names

In [10]:
cols_1 = []
for i in range(len(file1.columns)):
    cols_1.append(file1.columns[i].lower())
file1.columns = cols_1

file1.columns

Index(['customer', 'st', 'gender', 'education', 'customer lifetime value',
       'income', 'monthly premium auto', 'number of open complaints',
       'policy type', 'vehicle class', 'total claim amount'],
      dtype='object')

In [11]:
cols_2 = []
for i in range(len(file2.columns)):
    cols_2.append(file2.columns[i].lower())
file2.columns = cols_2

file2.columns

Index(['customer', 'st', 'gender', 'education', 'customer lifetime value',
       'income', 'monthly premium auto', 'number of open complaints',
       'total claim amount', 'policy type', 'vehicle class'],
      dtype='object')

In [12]:
cols_3 = []
for i in range(len(file3.columns)):
    cols_3.append(file3.columns[i].lower())
file3.columns = cols_3

file3.columns

Index(['customer', 'state', 'customer lifetime value', 'education', 'gender',
       'income', 'monthly premium auto', 'number of open complaints',
       'policy type', 'total claim amount', 'vehicle class'],
      dtype='object')

In [13]:
# Rearrange the columns in the dataframe as needed

In [14]:
file1.columns == file2.columns

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
       False, False])

In [15]:
file1.columns == file3.columns

array([ True, False, False,  True, False,  True,  True,  True,  True,
       False, False])

In [16]:
file2 = file2[['customer', 'st', 'gender', 'education', 'customer lifetime value',
       'income', 'monthly premium auto', 'number of open complaints',
       'policy type', 'vehicle class', 'total claim amount']]

In [17]:
file1.columns == file2.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [18]:
file3 = file3[['customer', 'state', 'gender', 'education','customer lifetime value',
       'income', 'monthly premium auto', 'number of open complaints',
       'policy type', 'vehicle class','total claim amount']]

In [19]:
file1.columns == file3.columns

array([ True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [20]:
file1 = file1.rename(columns={"st": "state"})

In [21]:
file2 = file2.rename(columns={"st": "state"})

In [22]:
file1.columns == file3.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [23]:
# Concatenate the three dataframes

In [24]:
data = pd.concat([file1, file2, file3], axis=0) 
data.shape
data.head()

customer       state gender             education customer lifetime value  \
0  RB50392  Washington    NaN                Master                     NaN   
1  QZ44356     Arizona      F              Bachelor              697953.59%   
2  AI49188      Nevada      F              Bachelor             1288743.17%   
3  WW63253  California      M              Bachelor              764586.18%   
4  GA49547  Washington      M  High School or Below              536307.65%   

    income  monthly premium auto number of open complaints     policy type  \
0      0.0                1000.0                    1/0/00   Personal Auto   
1      0.0                  94.0                    1/0/00   Personal Auto   
2  48767.0                 108.0                    1/0/00   Personal Auto   
3      0.0                 106.0                    1/0/00  Corporate Auto   
4  36357.0                  68.0                    1/0/00   Personal Auto   

   vehicle class  total claim amount  
0  Four-Door Car            2.704934  
1  Four-Door Car         1131.464935  
2   Two-Door Car          566.472247  
3            SUV          529.881344  
4  Four-Door Car           17.269323

In [25]:
# Which columns are numerical?

# Which columns are categorical?

In [26]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12074 entries, 0 to 7069
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   customer                   9137 non-null   object 
 1   state                      9137 non-null   object 
 2   gender                     9015 non-null   object 
 3   education                  9137 non-null   object 
 4   customer lifetime value    9130 non-null   object 
 5   income                     9137 non-null   float64
 6   monthly premium auto       9137 non-null   float64
 7   number of open complaints  9137 non-null   object 
 8   policy type                9137 non-null   object 
 9   vehicle class              9137 non-null   object 
 10  total claim amount         9137 non-null   float64
dtypes: float64(3), object(8)
memory usage: 1.1+ MB


In [27]:
categorical_columns = data.select_dtypes(include=['object']).columns
len(categorical_columns)

8

In [28]:
numerical_columns = data.select_dtypes(include=['float64']).columns
len(numerical_columns)

3

In [29]:
# Understand the meaning of all columns

In [30]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12074 entries, 0 to 7069
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   customer                   9137 non-null   object 
 1   state                      9137 non-null   object 
 2   gender                     9015 non-null   object 
 3   education                  9137 non-null   object 
 4   customer lifetime value    9130 non-null   object 
 5   income                     9137 non-null   float64
 6   monthly premium auto       9137 non-null   float64
 7   number of open complaints  9137 non-null   object 
 8   policy type                9137 non-null   object 
 9   vehicle class              9137 non-null   object 
 10  total claim amount         9137 non-null   float64
dtypes: float64(3), object(8)
memory usage: 1.1+ MB


In [31]:
# Perform the data cleaning operations mentioned so far in class

In [32]:
# Delete the column education and the number of open complaints from the dataframe.

In [33]:
data_cleaned = data.drop(['education','number of open complaints'], axis=1)
data_cleaned.head()

customer       state gender customer lifetime value   income  \
0  RB50392  Washington    NaN                     NaN      0.0   
1  QZ44356     Arizona      F              697953.59%      0.0   
2  AI49188      Nevada      F             1288743.17%  48767.0   
3  WW63253  California      M              764586.18%      0.0   
4  GA49547  Washington      M              536307.65%  36357.0   

   monthly premium auto     policy type  vehicle class  total claim amount  
0                1000.0   Personal Auto  Four-Door Car            2.704934  
1                  94.0   Personal Auto  Four-Door Car         1131.464935  
2                 108.0   Personal Auto   Two-Door Car          566.472247  
3                 106.0  Corporate Auto            SUV          529.881344  
4                  68.0   Personal Auto  Four-Door Car           17.269323

In [34]:
# Correct the values in the column customer lifetime value.
# They are given as a percent, so multiply them by 100 and change dtype to numerical type.

In [35]:
data_cleaned['customer lifetime value'].dtype

dtype('O')

In [36]:
data_cleaned['customer lifetime value'] = data_cleaned['customer lifetime value'].str.replace("%","")
data_cleaned.head()

customer       state gender customer lifetime value   income  \
0  RB50392  Washington    NaN                     NaN      0.0   
1  QZ44356     Arizona      F               697953.59      0.0   
2  AI49188      Nevada      F              1288743.17  48767.0   
3  WW63253  California      M               764586.18      0.0   
4  GA49547  Washington      M               536307.65  36357.0   

   monthly premium auto     policy type  vehicle class  total claim amount  
0                1000.0   Personal Auto  Four-Door Car            2.704934  
1                  94.0   Personal Auto  Four-Door Car         1131.464935  
2                 108.0   Personal Auto   Two-Door Car          566.472247  
3                 106.0  Corporate Auto            SUV          529.881344  
4                  68.0   Personal Auto  Four-Door Car           17.269323

In [37]:
data_cleaned['customer lifetime value'] = pd.to_numeric(data_cleaned['customer lifetime value'])

In [38]:
data_cleaned['customer lifetime value'].dtype

dtype('float64')

In [39]:
data_cleaned['customer lifetime value'] = data_cleaned['customer lifetime value']*100
data_cleaned.head()

customer       state gender  customer lifetime value   income  \
0  RB50392  Washington    NaN                      NaN      0.0   
1  QZ44356     Arizona      F               69795359.0      0.0   
2  AI49188      Nevada      F              128874317.0  48767.0   
3  WW63253  California      M               76458618.0      0.0   
4  GA49547  Washington      M               53630765.0  36357.0   

   monthly premium auto     policy type  vehicle class  total claim amount  
0                1000.0   Personal Auto  Four-Door Car            2.704934  
1                  94.0   Personal Auto  Four-Door Car         1131.464935  
2                 108.0   Personal Auto   Two-Door Car          566.472247  
3                 106.0  Corporate Auto            SUV          529.881344  
4                  68.0   Personal Auto  Four-Door Car           17.269323

In [40]:
# Check for duplicate rows in the data and remove if any.

In [41]:
len(data_cleaned)

12074

In [42]:
data_cleaned.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
7065    False
7066    False
7067    False
7068    False
7069    False
Length: 12074, dtype: bool

In [43]:
data_cleaned_new = data_cleaned.drop_duplicates()
len(data_cleaned_new)

9131

In [44]:
len(data_cleaned) - len(data_cleaned_new)

2943

In [45]:
# Filter out the data for customers who have an income of 0 or less.

In [47]:
perspective_customers = data[data['income']>0]
perspective_customers

customer       state gender             education  \
2     AI49188      Nevada      F              Bachelor   
4     GA49547  Washington      M  High School or Below   
5     OC83172      Oregon      F              Bachelor   
6     XZ87318      Oregon      F               College   
8     DY87989      Oregon      M              Bachelor   
...       ...         ...    ...                   ...   
7063  TF56202  California      M               College   
7064  YM19146  California      F               College   
7065  LA72316  California      M              Bachelor   
7066  PK87824  California      F               College   
7068  UP19263  California      M               College   

     customer lifetime value   income  monthly premium auto  \
2                1288743.17%  48767.0                 108.0   
4                 536307.65%  36357.0                  68.0   
5                 825629.78%  62902.0                  69.0   
6                 538089.86%  55350.0                  67.0   
8                2412750.40%  14072.0                  71.0   
...                      ...      ...                   ...   
7063             5032.165498  66367.0                  64.0   
7064             4100.398533  47761.0                 104.0   
7065             23405.98798  71941.0                  73.0   
7066             3096.511217  21604.0                  79.0   
7068             7524.442436  21941.0                  96.0   

     number of open complaints     policy type  vehicle class  \
2                       1/0/00   Personal Auto   Two-Door Car   
4                       1/0/00   Personal Auto  Four-Door Car   
5                       1/0/00   Personal Auto   Two-Door Car   
6                       1/0/00  Corporate Auto  Four-Door Car   
8                       1/0/00  Corporate Auto  Four-Door Car   
...                        ...             ...            ...   
7063                         0   Personal Auto   Two-Door Car   
7064                         0   Personal Auto  Four-Door Car   
7065                         0   Personal Auto  Four-Door Car   
7066                         0  Corporate Auto  Four-Door Car   
7068                         0   Personal Auto  Four-Door Car   

      total claim amount  
2             566.472247  
4              17.269323  
5             159.383042  
6             321.600000  
8             511.200000  
...                  ...  
7063          307.200000  
7064          541.282007  
7065          198.234764  
7066          379.200000  
7068          691.200000  

[6843 rows x 11 columns]